FROM microsoft/mssql-server-linux:latest

RUN mkdir -p /usr/config
WORKDIR /usr/config

ENV ACCEPT_EULA Y
ENV DB_NAME gpitfuture\-db\-dev
ENV DB_USER NHSD
ENV DB_PASSWORD DisruptTheMarket1!
ENV SA_PASSWORD Your_password456
ENV MSSQL_PID Express

# Copy all the integration-related scripts
COPY ["./configure-integration-db.sh", "./"]
COPY ["./integration-entrypoint.sh", "./"]
# Copy only the sql files we need
COPY ["/SQL/Create Database.sql","/SQL/ReferenceData.sql","/SQL/Create.sql", "sql/"]

RUN chmod +x /usr/config/integration-entrypoint.sh
RUN chmod +x /usr/config/configure-integration-db.sh
RUN ["/bin/bash", "./integration-entrypoint.sh"]

ENTRYPOINT ["/opt/mssql/bin/sqlservr"]

HEALTHCHECK --interval=15s CMD /opt/mssql-tools/bin/sqlcmd -U sa -P $SA_PASSWORD -Q "select 1" && grep -q "MSSQL CONFIG COMPLETE" ./config.log
