DELETE FROM [FrameworkCapabilities]
DELETE FROM [FrameworkSolutions]
UPDATE [Solution] SET SolutionDetailId = NULL
DELETE FROM [SolutionDetail]
DELETE FROM [SolutionEpic]
DELETE FROM [SolutionCapability]
DELETE FROM [Solution]
DELETE FROM [Epic]
DELETE FROM [Capability]
DELETE FROM [Supplier]
DELETE FROM [SupplierContact]
