DROP TABLE [FrameworkCapabilities]
DROP TABLE [Capability]
DROP TABLE [CapabilityStatus]
DROP TABLE [CapabilityCategory]
DROP TABLE [Framework]
DROP TABLE [SolutionCapability]
DROP TABLE [Solution]
DROP TABLE [SolutionCapabilityStatus]
