version: '3.5'

services:

  nhsd.buyingcatalogue.api:
    image: ${REGISTRY:-nhsd}/buying-catalogue/api:${TAG:-latest}
    container_name: nhsd_bcapi
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionStrings__BuyingCatalogue=${NHSD_BUYINGCATALOGUE_DB:-Data Source=localhost;Initial Catalog=buyingcatalogue;MultipleActiveResultSets=True;User Id=sa;Password=P@$$w0RD}
