:r ./InsertCommonValues.sql
:r ./InsertCalaogueItemTypes.sql
:r ./InsertFrameworks.sql
:r ./InsertCapabilities.sql
:r ./InsertEpics.sql
:r ./InsertSuppliers.sql
:r ./InsertSolutions.sql
:r ./DropImport.sql
:r ./DropPublish.sql
